version: "3.8"
services:
  mysql:
    container_name: diversifywebsite-mysql
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=wordpress
    image: mysql:5.7
    restart: always
    volumes:
      - database:/var/lib/mysql:delegated
  nginx-proxy:
    container_name: diversifywebsite-nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs:delegated,ro
      - ./configs/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:delegated,ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
  wordpress:
    container_name: diversifywebsite-wordpress
    depends_on:
      - mysql
    environment:
      - VIRTUAL_HOST=diversifywebsite.test,www.diversifywebsite.test
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_USER=wordpress
    image: wordpress:5.4
    restart: always
    volumes:
      - ./diversifywebsite:/var/www/html/wp-content/themes/diversifywebsite:cached
      - ./configs/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:delegated,ro
      - ./wordpress/wp-content/plugins:/var/www/html/wp-content/plugins:cached
      - ./wordpress/wp-content/uploads:/var/www/html/wp-content/uploads:delegated
volumes:
  database:
